### ISSUE TITLE
No post results displayed

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#44] opened 2020-06-18 19:58 UTC
**Describe the bug**
When you search for a tag, no results are displayed on the results page, although some are available.

**To Reproduce**
The bug cannot be reproduced consistently. It happens from time to time.

1. Go to 'Home'
2. Enter a value in the search bar
3. Press enter in the search bar

**Expected behavior**
The results for the serach tag should be displayed.

**Screenshots**
Since this error cannot be reproduced consistently, no screenshot is available. However, it looks as if no results are available.

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox
 - Version 77

**Smartphone (please complete the following information):**
Not used for testing.

**Additional context**
If you find a consistent way to reproduce this issue, please add it in the comments.

**Comment by jschurse** [comment] 2020-06-22 16:41
I think this issue should resolve itself.
This was caused by improper queries and updates after each part of the state was updated.
This has party been fixed by https://github.com/hochschule-darmstadt/einander-helfen/pull/62 and https://github.com/hochschule-darmstadt/einander-helfen/pull/67

We should verify this after said PR´s have been merged.

**Comment by jschurse** [comment] 2020-06-23 18:14
I tested the current release on our new staging server https://cai-einander-helfen-staging.fbi.h-da.de and can no longer reproduce this.

**Closed by jschurse** 2020-06-23 18:14 UTC
Labels: bug
