### ISSUE TITLE
Selecting autosuggested location via mouse click doesn't work with searching

### ISSUE THREAD

**Issue by KaiDrieHda** [hochschule-darmstadt/einander-helfen#358] opened 2021-05-21 13:19 UTC
**Describe the bug**
When on home page, if you type in the location field and select a suggested location from the list via mouse click (not by pressing ENTER) and then click on the search button, the result page doesn't show results for that location and the search mask is empty. This happens on desktop as well as smartphone.

**To Reproduce**
1. Go to home page
2. Type "Fra" into the location field
3. Select "Frankfurt" from the autosuggest list via mouse click
4. Click on the search button
5. See error

**Expected behavior**
It should search for the selected location. The name of the location should still be in the location field on the result page.

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser: all

**Additional context**
Might have been caused by the changes made for issue #298

**Comment by xcaverxiii** [comment] 2021-05-22 13:10
@KaiDrieHda On which is this issue found? Have you testes the expected behavior on the branch of #291 ?

**Comment by DianaPankratz** [comment] 2021-05-24 10:24
> @KaiDrieHda On which is this issue found? Have you tested the expected behavior on the branch of #291 ?

This bug was found on staging but it seems to be fixed on #291. So I will close this issue.

**Closed by DianaPankratz** 2021-05-24 10:24 UTC
Labels: bug, high
